function tf = modelsAreEqual(m1, m2)

assert(is(m1, 'Model'), 'm1 must be a Model')
assert(is(m2, 'Model'), 'm2 must be a Model')

if isequaln(m1.Type, m2.Type) && ...
        isequaln(m1.Compartments, m2.Compartments) && ...
        isequaln(m1.Name, m2.Name) && ...
        isequaln(m1.Parameters, m2.Parameters) && ...
        isequaln(m1.Seeds, m2.Seeds) && ...
        isequaln(m1.Inputs, m2.Inputs) && ...
        isequaln(m1.States, m2.States) && ...
        isequaln(m1.Reactions, m2.Reactions) && ...
        isequaln(m1.Outputs, m2.Outputs) && ...
        isequaln(m1.Rules, m2.Rules)
    tf = true;
else
    tf = false;
end
