function h = plotExperiment(m, sim, t, varargin)
% PLOTEXPERIMENT plots a simulation. 
%
% This function plots a simulation generated by simulate.
%
% h = subplotExperiment(m, sim) plots the output of the simulation
%       generated by simulate.
%
% h = subplotExperiment(m, sim, t) plots the output of the simulation
%       generated by simulate at the given times. 
%
% h = subplotExperiment(m, sim, t, ...) additional arguments are passed to
%       the plot command. For example:
%           plotExperiment(m, sim, t, 'd:');
%       will results in dotted lines with diamond markers at the time
%       points where the simution was evaluated 
%
% Arguments:
% m     The model that was simulated
% sim   The simulation returned from simulate
% t     The time interval to be plotted
%       If t is a scalar then simution will be plotted from time 0 to t
%       If t is length > 1 then the simution will be ploted only at times t
% h     A column vector of handles to lineseries graphics objects,
%       one handle per line
% 
% see also: simulate, plotExperiment, plot

% (c) 2010 David R Hagen, Joshua F Apgar, Jared E Toettcher, & Bruce Tidor
% This work is released under the MIT license.

if(nargin == 2)
    tPlot = sim.t;
elseif(length(t) == 1)
    tPlot = [sim.t(sim.t<t), t];
else
    tPlot = t;
end
   
yPlot = sim.y(tPlot);
h     = plot(tPlot, yPlot, varargin{:}, 'LineWidth', 2);
xlabel('Time');
ylabel('Concentration');
title(sim.Name);
legend({m.Outputs.Name});